Repository Kota-Karthik/twinTrim, pull requests merged in 2024-10, with the labels that each got.

#48 Your commit message
  tests/fileMetadata_test.py
Labels: gssoc-ext

#80 Added the logging feature
  twinTrim/flags.py
Labels: enhancement, level2, intermediate, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#68 Fixes #54 added code of conduct and linked it in readme.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, level1, gssoc-ext, changes requested

#74 Add --dry-run Functionality to TwinTrim for Safe Simulated Duplicate Removal
  README.md
  twinTrim/flags.py
Labels: enhancement, level2, intermediate, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#111 Improve User Experience by Implementing Multi-Select #88
  .gitignore
  twinTrim/dataStructures/__init__.py
  twinTrim/flags.py
Labels: enhancement, level2, intermediate, gssoc-ext, hacktoberfest-accepted

#121 Added unit tests for setMinFileSize method in FileFilter
  twinTrim/dataStructures/fileFilter.py
Labels: enhancement, level1, easy, gssoc-ext, hacktoberfest-accepted

#122 Created the compare_and_replace function tests
  .vscode/settings.json
  tests/allFileMetadata_compare_and_replace.py
Labels: enhancement, level2, intermediate, gssoc-ext, hacktoberfest-accepted

#145 [Enhancement] TwinTrim Website
  docs/Contributing.md
  docs/Features.md
  docs/How-It-Works.md
  docs/License.md
  docs/Usage.md
  docs/index.md
  mkdocs.yml
  requirements.txt
Labels: documentation, level1, gssoc-ext, hacktoberfest-accepted, changes requested

#152 Fix issue #3: Correctly mock handle_and_remove in compare_and_replace…
  tests/allFileMetadata_compare_and_replace.py
Labels: enhancement, level2, intermediate, gssoc-ext, hacktoberfest-accepted

#156 Fixes #11 Mock file operations Tests
  tests/test_fileMetadata.py
Labels: enhancement, level2, intermediate, gssoc-ext, hacktoberfest-accepted

#158 Added normalised expected path to tackle windows specific error.
  tests/test_flagController.py
Labels: hacktoberfest, hacktoberfest-accepted
